version: '3.9'

services:

  web:
    image: dmvaled/gbooks-django
    command: gunicorn --bind 0.0.0.0:8000 gbooks.wsgi:application --workers=2
    volumes:
      - static_volume:/gbooks/static
    #      - media_volume:/media
    expose:
      - "8000"
    networks:
      - django-network

  nginx:
    image: dmvaled/gbooks-nginx
    restart: always
    volumes:
      - static_volume:/gbooks/static
    #      - media_volume:/app/media
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - django-network

networks:
  django-network:
    name: django-network

volumes:
  static_volume:
  #  media_volume:
