name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          ENVIRONMENT: development
          SECRET_KEY: f4@#c!suh2q3n84y8.,b_#w%1p6vr$njc9117h7#u4';$yy^*4t8g7&$%h7d
          ALLOWED_HOSTS: localhost,127.0.0.1
      - name: Run Tests
        run: |
          python manage.py test
